# Generated by Django 2.1.1 on 2019-05-12 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=25)),
                ('product_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], default='Gold', max_length=25)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 5, 12, 4, 56, 47, 703211), null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
