# Generated by Django 2.1.1 on 2019-05-12 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(blank=True, max_length=50)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 5, 12, 4, 56, 47, 704211), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderquantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.CharField(max_length=20)),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Products')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='order_quantity',
            field=models.ManyToManyField(null=True, to='customers.Orderquantity'),
        ),
    ]
