# Generated by Django 2.1.1 on 2019-06-29 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 10, 43, 49, 222212), null=True),
        ),
    ]
